"""suscripciones y cupo de funciones

Revision ID: 7545b45fbc04
Revises: e7b419a28785
Create Date: 2026-08-27 14:28:17.898109
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '7545b45fbc04'
down_revision = 'e7b419a28785'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_usage',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('feature', sa.String(length=32), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_feature_usage_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_usage')),
    sa.UniqueConstraint('user_id', 'feature', 'period_start', name=op.f('uq_feature_usage_user_id'))
    )
    with op.batch_alter_table('feature_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_usage_user_id'), ['user_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('plan', sa.String(length=16), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('cancelled_at', sa.Date(), nullable=True),
    sa.Column('in_grace_period', sa.Boolean(), nullable=False),
    sa.Column('store', sa.String(length=16), nullable=True),
    sa.Column('store_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('billing_country', sa.String(length=2), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('feature_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_usage_user_id'))

    op.drop_table('feature_usage')
    # ### end Alembic commands ###
