"""esquema inicial

Revision ID: e7b419a28785
Revises: 
Create Date: 2026-08-27 08:58:29.112090
"""
from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = 'e7b419a28785'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('size_ml', sa.Float(), nullable=True),
    sa.Column('price_minor_units', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('available_in', sa.JSON(), nullable=False),
    sa.Column('inci_raw', sa.Text(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('consents',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.Enum('TERMS', 'PRIVACY', 'PHOTO_PROCESSING', 'MODEL_TRAINING', 'STYLIST_SHARING', 'ANONYMOUS_AGGREGATE', name='consentpurpose'), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_consents_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consents')),
    sa.UniqueConstraint('user_id', 'purpose', 'version', name=op.f('uq_consents_user_id'))
    )
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consents_user_id'), ['user_id'], unique=False)

    op.create_table('hair_profiles',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('depth_level', sa.String(length=16), nullable=False),
    sa.Column('wash_frequency_days', sa.Float(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('water_hardness_ppm', sa.Float(), nullable=True),
    sa.Column('uses_heat', sa.Boolean(), nullable=False),
    sa.Column('owns_diffuser', sa.Boolean(), nullable=False),
    sa.Column('protective_style', sa.String(length=32), nullable=False),
    sa.Column('habits', sa.JSON(), nullable=False),
    sa.Column('onboarding_essential_done', sa.Boolean(), nullable=False),
    sa.Column('completeness', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_hair_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hair_profiles'))
    )
    with op.batch_alter_table('hair_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hair_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('chemical_events',
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('zones', sa.JSON(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['hair_profiles.id'], name=op.f('fk_chemical_events_profile_id_hair_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chemical_events'))
    )
    with op.batch_alter_table('chemical_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chemical_events_profile_id'), ['profile_id'], unique=False)

    op.create_table('experiments',
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('question_key', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('controlled_variables', sa.JSON(), nullable=False),
    sa.Column('target_repetitions_per_arm', sa.Integer(), nullable=False),
    sa.Column('shared_anonymously', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['hair_profiles.id'], name=op.f('fk_experiments_profile_id_hair_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiments_profile_id'), ['profile_id'], unique=False)

    op.create_table('goals',
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['hair_profiles.id'], name=op.f('fk_goals_profile_id_hair_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goals')),
    sa.UniqueConstraint('profile_id', 'kind', name=op.f('uq_goals_profile_id'))
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_profile_id'), ['profile_id'], unique=False)

    op.create_table('hair_zones',
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('zone', sa.Enum('FRONTAL_HAIRLINE', 'BANGS', 'FRONT_LEFT', 'FRONT_RIGHT', 'LEFT_TEMPLE', 'RIGHT_TEMPLE', 'SIDE_UPPER_LEFT', 'SIDE_UPPER_RIGHT', 'SIDE_LOWER_LEFT', 'SIDE_LOWER_RIGHT', 'CROWN', 'BACK_CROWN', 'OCCIPITAL', 'NAPE', 'ENDS', name='zone'), nullable=False),
    sa.Column('measurements', sa.JSON(), nullable=False),
    sa.Column('damage_signs', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['hair_profiles.id'], name=op.f('fk_hair_zones_profile_id_hair_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hair_zones')),
    sa.UniqueConstraint('profile_id', 'zone', name=op.f('uq_hair_zones_profile_id'))
    )
    with op.batch_alter_table('hair_zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hair_zones_profile_id'), ['profile_id'], unique=False)

    op.create_table('inventory_items',
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=True),
    sa.Column('custom_name', sa.String(length=240), nullable=True),
    sa.Column('custom_category', sa.String(length=32), nullable=True),
    sa.Column('custom_inci', sa.Text(), nullable=True),
    sa.Column('amount_left_ratio', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.Date(), nullable=True),
    sa.Column('pao_months', sa.Integer(), nullable=True),
    sa.Column('disliked', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_items_product_id_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['hair_profiles.id'], name=op.f('fk_inventory_items_profile_id_hair_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_items'))
    )
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_items_profile_id'), ['profile_id'], unique=False)

    op.create_table('routines',
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['hair_profiles.id'], name=op.f('fk_routines_profile_id_hair_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routines'))
    )
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routines_profile_id'), ['profile_id'], unique=False)

    op.create_table('scans',
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ANALYSING', 'AWAITING_CONFIRMATION', 'CONFIRMED', 'FAILED', name='scanstatus'), nullable=False),
    sa.Column('quality_report', sa.JSON(), nullable=False),
    sa.Column('interpretation', sa.JSON(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['hair_profiles.id'], name=op.f('fk_scans_profile_id_hair_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scans'))
    )
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scans_profile_id'), ['profile_id'], unique=False)

    op.create_table('sensitivities',
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('inci_name', sa.String(length=240), nullable=False),
    sa.Column('reported_reaction', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['hair_profiles.id'], name=op.f('fk_sensitivities_profile_id_hair_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensitivities'))
    )
    with op.batch_alter_table('sensitivities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensitivities_profile_id'), ['profile_id'], unique=False)

    op.create_table('twin_snapshots',
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['hair_profiles.id'], name=op.f('fk_twin_snapshots_profile_id_hair_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_twin_snapshots'))
    )
    with op.batch_alter_table('twin_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_twin_snapshots_profile_id'), ['profile_id'], unique=False)

    op.create_table('experiment_arms',
    sa.Column('experiment_id', sa.String(length=32), nullable=False),
    sa.Column('label_key', sa.String(length=120), nullable=False),
    sa.Column('product_ids', sa.JSON(), nullable=False),
    sa.Column('technique_ids', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_experiment_arms_experiment_id_experiments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_arms')),
    sa.UniqueConstraint('experiment_id', 'label_key', name=op.f('uq_experiment_arms_experiment_id'))
    )
    with op.batch_alter_table('experiment_arms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiment_arms_experiment_id'), ['experiment_id'], unique=False)

    op.create_table('scan_photos',
    sa.Column('scan_id', sa.String(length=32), nullable=False),
    sa.Column('angle', sa.String(length=32), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('quality', sa.JSON(), nullable=False),
    sa.Column('face_cropped', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_scan_photos_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_photos'))
    )
    with op.batch_alter_table('scan_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_photos_scan_id'), ['scan_id'], unique=False)

    op.create_table('zone_measurement_history',
    sa.Column('zone_row_id', sa.String(length=32), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('replaced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['zone_row_id'], ['hair_zones.id'], name=op.f('fk_zone_measurement_history_zone_row_id_hair_zones'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zone_measurement_history'))
    )
    with op.batch_alter_table('zone_measurement_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zone_measurement_history_zone_row_id'), ['zone_row_id'], unique=False)

    op.create_table('journal_entries',
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('product_ids', sa.JSON(), nullable=False),
    sa.Column('technique_ids', sa.JSON(), nullable=False),
    sa.Column('amounts_ml', sa.JSON(), nullable=False),
    sa.Column('weather', sa.JSON(), nullable=False),
    sa.Column('ratings', sa.JSON(), nullable=False),
    sa.Column('photo_keys', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('experiment_arm_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_arm_id'], ['experiment_arms.id'], name=op.f('fk_journal_entries_experiment_arm_id_experiment_arms'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['hair_profiles.id'], name=op.f('fk_journal_entries_profile_id_hair_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_entries'))
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_entry_date'), ['entry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_profile_id'), ['profile_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_profile_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_entry_date'))

    op.drop_table('journal_entries')
    with op.batch_alter_table('zone_measurement_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zone_measurement_history_zone_row_id'))

    op.drop_table('zone_measurement_history')
    with op.batch_alter_table('scan_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_photos_scan_id'))

    op.drop_table('scan_photos')
    with op.batch_alter_table('experiment_arms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiment_arms_experiment_id'))

    op.drop_table('experiment_arms')
    with op.batch_alter_table('twin_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_twin_snapshots_profile_id'))

    op.drop_table('twin_snapshots')
    with op.batch_alter_table('sensitivities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensitivities_profile_id'))

    op.drop_table('sensitivities')
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scans_profile_id'))

    op.drop_table('scans')
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routines_profile_id'))

    op.drop_table('routines')
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_items_profile_id'))

    op.drop_table('inventory_items')
    with op.batch_alter_table('hair_zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hair_zones_profile_id'))

    op.drop_table('hair_zones')
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_profile_id'))

    op.drop_table('goals')
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiments_profile_id'))

    op.drop_table('experiments')
    with op.batch_alter_table('chemical_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chemical_events_profile_id'))

    op.drop_table('chemical_events')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_jti'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('hair_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hair_profiles_user_id'))

    op.drop_table('hair_profiles')
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consents_user_id'))

    op.drop_table('consents')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_category'))
        batch_op.drop_index(batch_op.f('ix_products_brand'))

    op.drop_table('products')
    # ### end Alembic commands ###
